[2023-03-11T15:41:29.368+0000] {processor.py:153} INFO - Started process (PID=47) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:41:29.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:41:29.373+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:41:29.373+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:41:29.439+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:41:29.427+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:41:29.445+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:41:29.474+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.109 seconds
[2023-03-11T15:41:59.612+0000] {processor.py:153} INFO - Started process (PID=111) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:41:59.614+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:41:59.615+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:41:59.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:41:59.668+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:41:59.659+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:41:59.673+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:41:59.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.084 seconds
[2023-03-11T15:42:30.002+0000] {processor.py:153} INFO - Started process (PID=155) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:42:30.008+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:42:30.011+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:42:30.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:42:30.095+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:42:30.079+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:42:30.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:42:30.124+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.126 seconds
[2023-03-11T15:43:00.277+0000] {processor.py:153} INFO - Started process (PID=220) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:43:00.279+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:43:00.280+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:43:00.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:43:00.413+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:43:00.393+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:43:00.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:43:00.448+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.175 seconds
[2023-03-11T15:43:30.686+0000] {processor.py:153} INFO - Started process (PID=264) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:43:30.689+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:43:30.690+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:43:30.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:43:30.730+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:43:30.722+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:43:30.734+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:43:30.754+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.069 seconds
[2023-03-11T15:44:01.460+0000] {processor.py:153} INFO - Started process (PID=328) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:44:01.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:44:01.467+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:44:01.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:44:01.518+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:44:01.508+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:44:01.523+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:44:01.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.081 seconds
[2023-03-11T15:44:32.372+0000] {processor.py:153} INFO - Started process (PID=372) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:44:32.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:44:32.376+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:44:32.375+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:44:32.425+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:44:32.411+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:44:32.435+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:44:32.453+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.083 seconds
[2023-03-11T15:45:03.476+0000] {processor.py:153} INFO - Started process (PID=437) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:45:03.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:45:03.480+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:45:03.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:45:03.564+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:45:03.554+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:45:03.568+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:45:03.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.109 seconds
[2023-03-11T15:45:33.778+0000] {processor.py:153} INFO - Started process (PID=481) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:45:33.780+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:45:33.781+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:45:33.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:45:33.821+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:45:33.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:45:33.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:45:33.841+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.065 seconds
[2023-03-11T15:46:03.952+0000] {processor.py:153} INFO - Started process (PID=545) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:46:03.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:46:03.959+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:46:03.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:46:04.063+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:46:04.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:46:04.074+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:46:04.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.146 seconds
[2023-03-11T15:46:34.322+0000] {processor.py:153} INFO - Started process (PID=598) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:46:34.325+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:46:34.326+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:46:34.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:46:34.400+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:46:34.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:46:34.406+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:46:34.426+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.107 seconds
[2023-03-11T15:51:22.918+0000] {processor.py:153} INFO - Started process (PID=615) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:51:22.921+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:51:22.922+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:51:22.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:51:22.995+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:51:22.980+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:51:23.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:51:23.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.121 seconds
[2023-03-11T15:51:53.757+0000] {processor.py:153} INFO - Started process (PID=679) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:51:53.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:51:53.761+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:51:53.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:51:53.851+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:51:53.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:51:53.858+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:51:53.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.121 seconds
[2023-03-11T15:52:24.137+0000] {processor.py:153} INFO - Started process (PID=722) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:52:24.140+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:52:24.143+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:52:24.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:52:24.256+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:52:24.237+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:52:24.264+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:52:24.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.149 seconds
[2023-03-11T15:52:54.408+0000] {processor.py:153} INFO - Started process (PID=785) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:52:54.413+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:52:54.415+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:52:54.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:52:54.545+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:52:54.521+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:52:54.555+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:52:54.579+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.174 seconds
[2023-03-11T15:53:24.665+0000] {processor.py:153} INFO - Started process (PID=829) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:53:24.668+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:53:24.669+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:53:24.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:53:24.716+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:53:24.707+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:53:24.719+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:53:24.737+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.075 seconds
[2023-03-11T15:53:54.956+0000] {processor.py:153} INFO - Started process (PID=893) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:53:54.961+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:53:54.965+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:53:54.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:53:55.127+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:53:55.099+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:53:55.137+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:53:55.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.207 seconds
[2023-03-11T15:54:25.253+0000] {processor.py:153} INFO - Started process (PID=937) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:54:25.255+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-03-11T15:54:25.256+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:54:25.255+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:54:25.305+0000] {logging_mixin.py:137} INFO - [2023-03-11T15:54:25.295+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-03-11T15:54:25.310+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-03-11T15:54:25.327+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.076 seconds
