[2023-02-23T00:09:15.072+0000] {processor.py:153} INFO - Started process (PID=51) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:09:15.076+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:09:15.078+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:09:15.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:09:15.161+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:09:15.143+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:09:15.168+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:09:15.276+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.207 seconds
[2023-02-23T00:09:45.509+0000] {processor.py:153} INFO - Started process (PID=133) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:09:45.513+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:09:45.514+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:09:45.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:09:45.603+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:09:45.585+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:09:45.610+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:09:45.630+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.124 seconds
[2023-02-23T00:10:16.117+0000] {processor.py:153} INFO - Started process (PID=177) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:10:16.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:10:16.121+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:10:16.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:10:16.156+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:10:16.149+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:10:16.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:10:16.179+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.065 seconds
[2023-02-23T00:10:46.726+0000] {processor.py:153} INFO - Started process (PID=242) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:10:46.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:10:46.728+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:10:46.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:10:46.795+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:10:46.778+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:10:46.800+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:10:46.816+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.092 seconds
[2023-02-23T00:11:17.160+0000] {processor.py:153} INFO - Started process (PID=286) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:11:17.162+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:11:17.163+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:11:17.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:11:17.197+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:11:17.189+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:11:17.201+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:11:17.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.062 seconds
[2023-02-23T00:11:47.671+0000] {processor.py:153} INFO - Started process (PID=350) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:11:47.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:11:47.673+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:11:47.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:11:47.710+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:11:47.702+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:11:47.713+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:11:47.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.061 seconds
[2023-02-23T00:12:18.164+0000] {processor.py:153} INFO - Started process (PID=394) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:12:18.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:12:18.167+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:12:18.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:12:18.200+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:12:18.194+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:12:18.204+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:12:18.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.057 seconds
[2023-02-23T00:12:48.989+0000] {processor.py:153} INFO - Started process (PID=458) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:12:48.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:12:48.993+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:12:48.993+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:12:49.055+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:12:49.043+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:12:49.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:12:49.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.093 seconds
[2023-02-23T00:13:19.753+0000] {processor.py:153} INFO - Started process (PID=502) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:13:19.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:13:19.758+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:13:19.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:13:19.792+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:13:19.786+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:13:19.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:13:19.812+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.061 seconds
[2023-02-23T00:13:50.574+0000] {processor.py:153} INFO - Started process (PID=566) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:13:50.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:13:50.577+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:13:50.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:13:50.629+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:13:50.614+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:13:50.634+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:13:50.654+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.082 seconds
[2023-02-23T00:14:21.178+0000] {processor.py:153} INFO - Started process (PID=616) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:14:21.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:14:21.184+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:14:21.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:14:21.257+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:14:21.243+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:14:21.263+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:14:21.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.108 seconds
[2023-02-23T00:14:51.716+0000] {processor.py:153} INFO - Started process (PID=673) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:14:51.722+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T00:14:51.726+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:14:51.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:14:51.887+0000] {logging_mixin.py:137} INFO - [2023-02-23T00:14:51.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T00:14:51.892+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T00:14:51.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.198 seconds
[2023-02-23T21:02:27.688+0000] {processor.py:153} INFO - Started process (PID=63) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:02:27.692+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:02:27.695+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:02:27.694+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:02:27.817+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:02:27.802+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:02:27.826+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:02:27.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.179 seconds
[2023-02-23T21:02:58.233+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:02:58.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:02:58.240+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:02:58.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:02:58.309+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:02:58.295+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:02:58.316+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:02:58.340+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.111 seconds
[2023-02-23T21:03:28.947+0000] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:03:28.961+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:03:28.963+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:03:28.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:03:29.025+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:03:29.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:03:29.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:03:29.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.109 seconds
[2023-02-23T21:03:59.704+0000] {processor.py:153} INFO - Started process (PID=214) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:03:59.707+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:03:59.708+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:03:59.708+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:03:59.765+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:03:59.750+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:03:59.771+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:03:59.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.086 seconds
[2023-02-23T21:04:30.390+0000] {processor.py:153} INFO - Started process (PID=267) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:04:30.393+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:04:30.394+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:04:30.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:04:30.490+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:04:30.479+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:04:30.496+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:04:30.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.128 seconds
[2023-02-23T21:05:00.810+0000] {processor.py:153} INFO - Started process (PID=322) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:05:00.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:05:00.814+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:05:00.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:05:00.872+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:05:00.860+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:05:00.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:05:00.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.087 seconds
[2023-02-23T21:05:31.475+0000] {processor.py:153} INFO - Started process (PID=375) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:05:31.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-23T21:05:31.481+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:05:31.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:05:31.532+0000] {logging_mixin.py:137} INFO - [2023-02-23T21:05:31.521+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-23T21:05:31.536+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-23T21:05:31.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.080 seconds
