[2022-12-15T00:00:16.708+0000] {processor.py:153} INFO - Started process (PID=2101) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:00:16.710+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:00:16.711+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:00:16.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:00:16.755+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:00:16.747+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:00:16.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:00:16.778+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.072 seconds
[2022-12-15T00:00:46.887+0000] {processor.py:153} INFO - Started process (PID=2166) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:00:46.890+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:00:46.891+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:00:46.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:00:46.968+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:00:46.953+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:00:46.972+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:00:47.013+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.129 seconds
[2022-12-15T00:01:17.454+0000] {processor.py:153} INFO - Started process (PID=2219) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:01:17.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:01:17.466+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:01:17.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:01:17.531+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:01:17.517+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:01:17.538+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:01:17.600+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.149 seconds
[2022-12-15T00:01:48.241+0000] {processor.py:153} INFO - Started process (PID=2275) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:01:48.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:01:48.246+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:01:48.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:01:48.319+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:01:48.310+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:01:48.323+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:01:48.341+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.103 seconds
[2022-12-15T00:02:19.165+0000] {processor.py:153} INFO - Started process (PID=2339) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:02:19.168+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:02:19.169+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:02:19.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:02:19.266+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:02:19.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:02:19.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:02:19.297+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.135 seconds
[2022-12-15T00:02:50.011+0000] {processor.py:153} INFO - Started process (PID=2383) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:02:50.014+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:02:50.015+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:02:50.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:02:50.113+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:02:50.093+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:02:50.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:02:50.137+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.128 seconds
[2022-12-15T00:03:20.778+0000] {processor.py:153} INFO - Started process (PID=2447) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:03:20.781+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:03:20.781+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:03:20.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:03:20.828+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:03:20.818+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:03:20.831+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:03:20.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.073 seconds
[2022-12-15T00:03:50.993+0000] {processor.py:153} INFO - Started process (PID=2491) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:03:50.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:03:50.997+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:03:50.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:03:51.038+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:03:51.029+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:03:51.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:03:51.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.069 seconds
[2022-12-15T00:04:21.183+0000] {processor.py:153} INFO - Started process (PID=2555) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:04:21.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:04:21.187+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:04:21.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:04:21.264+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:04:21.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:04:21.269+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:04:21.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.108 seconds
[2022-12-15T00:04:51.346+0000] {processor.py:153} INFO - Started process (PID=2599) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:04:51.348+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:04:51.350+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:04:51.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:04:51.398+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:04:51.388+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:04:51.402+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:04:51.421+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.077 seconds
[2022-12-15T00:05:21.556+0000] {processor.py:153} INFO - Started process (PID=2663) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:05:21.558+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:05:21.559+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:05:21.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:05:21.630+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:05:21.616+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:05:21.636+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:05:21.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.100 seconds
[2022-12-15T00:05:51.770+0000] {processor.py:153} INFO - Started process (PID=2706) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:05:51.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:05:51.777+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:05:51.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:05:51.844+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:05:51.833+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:05:51.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:05:51.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.098 seconds
[2022-12-15T00:06:21.972+0000] {processor.py:153} INFO - Started process (PID=2770) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:06:21.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:06:21.975+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:06:21.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:06:22.023+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:06:22.013+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:06:22.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:06:22.046+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.077 seconds
[2022-12-15T00:06:52.727+0000] {processor.py:153} INFO - Started process (PID=2814) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:06:52.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:06:52.731+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:06:52.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:06:52.814+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:06:52.797+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:06:52.822+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:06:52.845+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.121 seconds
[2022-12-15T00:07:23.148+0000] {processor.py:153} INFO - Started process (PID=2878) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:07:23.152+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:07:23.153+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:07:23.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:07:23.249+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:07:23.232+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:07:23.255+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:07:23.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.142 seconds
[2022-12-15T00:07:53.600+0000] {processor.py:153} INFO - Started process (PID=2924) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:07:53.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:07:53.613+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:07:53.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:07:53.733+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:07:53.705+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:07:53.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:07:53.773+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.176 seconds
[2022-12-15T00:08:24.089+0000] {processor.py:153} INFO - Started process (PID=2988) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:08:24.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:08:24.095+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:08:24.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:08:24.217+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:08:24.194+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:08:24.226+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:08:24.260+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.176 seconds
[2022-12-15T00:08:54.880+0000] {processor.py:153} INFO - Started process (PID=3032) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:08:54.884+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:08:54.885+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:08:54.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:08:54.924+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:08:54.917+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:08:54.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:08:54.946+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.068 seconds
[2022-12-15T00:09:25.044+0000] {processor.py:153} INFO - Started process (PID=3097) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:09:25.047+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:09:25.049+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:09:25.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:09:25.116+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:09:25.103+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:09:25.121+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:09:25.142+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.103 seconds
[2022-12-15T00:09:55.217+0000] {processor.py:153} INFO - Started process (PID=3148) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:09:55.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:09:55.221+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:09:55.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:09:55.285+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:09:55.272+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:09:55.292+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:09:55.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.096 seconds
[2022-12-15T00:10:25.952+0000] {processor.py:153} INFO - Started process (PID=3206) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:10:25.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:10:25.955+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:10:25.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:10:25.994+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:10:25.986+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:10:25.997+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:10:26.016+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.067 seconds
[2022-12-15T00:10:56.774+0000] {processor.py:153} INFO - Started process (PID=3269) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:10:56.776+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:10:56.777+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:10:56.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:10:56.857+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:10:56.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:10:56.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:10:56.885+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.113 seconds
[2022-12-15T00:11:27.492+0000] {processor.py:153} INFO - Started process (PID=3313) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:11:27.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:11:27.495+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:11:27.495+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:11:27.588+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:11:27.567+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:11:27.596+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:11:27.616+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.127 seconds
[2022-12-15T00:11:58.330+0000] {processor.py:153} INFO - Started process (PID=3377) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:11:58.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:11:58.335+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:11:58.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:11:58.434+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:11:58.411+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:11:58.441+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:11:58.458+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.134 seconds
[2022-12-15T00:12:28.610+0000] {processor.py:153} INFO - Started process (PID=3421) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:12:28.614+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:12:28.616+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:12:28.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:12:28.709+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:12:28.692+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:12:28.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:12:28.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.138 seconds
[2022-12-15T00:12:59.032+0000] {processor.py:153} INFO - Started process (PID=3486) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:12:59.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:12:59.038+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:12:59.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:12:59.131+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:12:59.109+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:12:59.138+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:12:59.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.129 seconds
[2022-12-15T00:13:29.716+0000] {processor.py:153} INFO - Started process (PID=3530) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:13:29.720+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:13:29.721+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:13:29.721+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:13:29.823+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:13:29.808+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:13:29.827+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:13:29.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.140 seconds
[2022-12-15T00:14:00.493+0000] {processor.py:153} INFO - Started process (PID=3594) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:14:00.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:14:00.498+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:14:00.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:14:00.592+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:14:00.572+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:14:00.600+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:14:00.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.127 seconds
[2022-12-15T00:14:31.305+0000] {processor.py:153} INFO - Started process (PID=3637) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:14:31.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:14:31.310+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:14:31.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:14:31.401+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:14:31.383+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:14:31.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:14:31.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.130 seconds
[2022-12-15T00:15:02.116+0000] {processor.py:153} INFO - Started process (PID=3701) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:15:02.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:15:02.122+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:15:02.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:15:02.224+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:15:02.205+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:15:02.231+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:15:02.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.147 seconds
[2022-12-15T00:15:32.777+0000] {processor.py:153} INFO - Started process (PID=3765) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:15:32.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:15:32.780+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:15:32.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:15:32.844+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:15:32.832+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:15:32.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:15:32.866+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.092 seconds
[2022-12-15T00:16:03.247+0000] {processor.py:153} INFO - Started process (PID=3809) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:16:03.249+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:16:03.250+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:16:03.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:16:03.323+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:16:03.307+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:16:03.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:16:03.347+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T00:16:34.052+0000] {processor.py:153} INFO - Started process (PID=3872) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:16:34.055+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:16:34.056+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:16:34.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:16:34.148+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:16:34.130+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:16:34.156+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:16:34.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.131 seconds
[2022-12-15T00:17:04.792+0000] {processor.py:153} INFO - Started process (PID=3916) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:17:04.797+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:17:04.798+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:17:04.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:17:04.878+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:17:04.862+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:17:04.885+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:17:04.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.117 seconds
[2022-12-15T00:17:35.533+0000] {processor.py:153} INFO - Started process (PID=3981) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:17:35.536+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:17:35.538+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:17:35.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:17:35.629+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:17:35.611+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:17:35.637+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:17:35.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.123 seconds
[2022-12-15T00:18:06.333+0000] {processor.py:153} INFO - Started process (PID=4025) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:18:06.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:18:06.338+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:18:06.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:18:06.427+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:18:06.406+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:18:06.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:18:06.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.125 seconds
[2022-12-15T00:18:37.037+0000] {processor.py:153} INFO - Started process (PID=4089) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:18:37.039+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:18:37.040+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:18:37.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:18:37.108+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:18:37.090+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:18:37.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:18:37.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.109 seconds
[2022-12-15T00:19:07.786+0000] {processor.py:153} INFO - Started process (PID=4153) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:19:07.790+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:19:07.791+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:19:07.790+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:19:07.847+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:19:07.833+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:19:07.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:19:07.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.087 seconds
[2022-12-15T00:19:38.601+0000] {processor.py:153} INFO - Started process (PID=4198) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:19:38.605+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:19:38.606+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:19:38.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:19:38.694+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:19:38.675+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:19:38.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:19:38.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.162 seconds
[2022-12-15T00:20:09.417+0000] {processor.py:153} INFO - Started process (PID=4262) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:20:09.420+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:20:09.422+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:20:09.421+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:20:09.507+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:20:09.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:20:09.513+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:20:09.531+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.118 seconds
[2022-12-15T00:20:40.156+0000] {processor.py:153} INFO - Started process (PID=4306) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:20:40.159+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:20:40.160+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:20:40.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:20:40.212+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:20:40.201+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:20:40.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:20:40.234+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.081 seconds
[2022-12-15T00:21:10.446+0000] {processor.py:153} INFO - Started process (PID=4370) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:21:10.450+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:21:10.451+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:21:10.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:21:10.539+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:21:10.522+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:21:10.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:21:10.564+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.120 seconds
[2022-12-15T00:21:41.305+0000] {processor.py:153} INFO - Started process (PID=4414) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:21:41.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:21:41.310+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:21:41.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:21:41.440+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:21:41.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:21:41.448+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:21:41.468+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.166 seconds
[2022-12-15T00:22:12.199+0000] {processor.py:153} INFO - Started process (PID=4478) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:22:12.203+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:22:12.204+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:22:12.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:22:12.251+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:22:12.239+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:22:12.254+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:22:12.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.073 seconds
[2022-12-15T00:22:42.963+0000] {processor.py:153} INFO - Started process (PID=4522) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:22:42.965+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:22:42.967+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:22:42.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:22:43.040+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:22:43.026+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:22:43.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:22:43.068+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.107 seconds
[2022-12-15T00:23:13.309+0000] {processor.py:153} INFO - Started process (PID=4587) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:23:13.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:23:13.312+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:23:13.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:23:13.397+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:23:13.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:23:13.404+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:23:13.421+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.115 seconds
[2022-12-15T00:23:44.071+0000] {processor.py:153} INFO - Started process (PID=4631) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:23:44.074+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:23:44.075+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:23:44.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:23:44.130+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:23:44.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:23:44.134+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:23:44.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.119 seconds
[2022-12-15T00:24:14.366+0000] {processor.py:153} INFO - Started process (PID=4695) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:24:14.370+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:24:14.371+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:24:14.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:24:14.451+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:24:14.431+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:24:14.458+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:24:14.476+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.113 seconds
[2022-12-15T00:24:45.124+0000] {processor.py:153} INFO - Started process (PID=4759) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:24:45.126+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:24:45.128+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:24:45.127+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:24:45.202+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:24:45.188+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:24:45.208+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:24:45.224+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T00:25:15.866+0000] {processor.py:153} INFO - Started process (PID=4803) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:25:15.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:25:15.870+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:25:15.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:25:15.944+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:25:15.929+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:25:15.950+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:25:15.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.103 seconds
[2022-12-15T00:25:46.609+0000] {processor.py:153} INFO - Started process (PID=4867) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:25:46.612+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:25:46.613+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:25:46.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:25:46.684+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:25:46.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:25:46.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:25:46.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.099 seconds
[2022-12-15T00:26:16.904+0000] {processor.py:153} INFO - Started process (PID=4912) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:26:16.907+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:26:16.908+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:26:16.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:26:16.986+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:26:16.973+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:26:16.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:26:17.011+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.111 seconds
[2022-12-15T00:26:47.123+0000] {processor.py:153} INFO - Started process (PID=4976) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:26:47.126+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:26:47.127+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:26:47.127+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:26:47.232+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:26:47.215+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:26:47.239+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:26:47.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.143 seconds
[2022-12-15T00:27:17.362+0000] {processor.py:153} INFO - Started process (PID=5021) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:27:17.364+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:27:17.366+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:27:17.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:27:17.408+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:27:17.399+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:27:17.412+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:27:17.428+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.068 seconds
[2022-12-15T00:27:47.602+0000] {processor.py:153} INFO - Started process (PID=5086) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:27:47.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:27:47.607+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:27:47.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:27:47.668+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:27:47.655+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:27:47.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:27:47.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.093 seconds
[2022-12-15T00:28:17.789+0000] {processor.py:153} INFO - Started process (PID=5131) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:28:17.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:28:17.793+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:28:17.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:28:17.859+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:28:17.847+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:28:17.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:28:17.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.098 seconds
[2022-12-15T00:28:48.138+0000] {processor.py:153} INFO - Started process (PID=5195) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:28:48.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:28:48.143+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:28:48.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:28:48.215+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:28:48.204+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:28:48.219+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:28:48.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T00:29:18.902+0000] {processor.py:153} INFO - Started process (PID=5239) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:29:18.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:29:18.906+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:29:18.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:29:18.981+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:29:18.966+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:29:18.987+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:29:19.006+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.107 seconds
[2022-12-15T00:29:49.848+0000] {processor.py:153} INFO - Started process (PID=5303) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:29:49.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:29:49.851+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:29:49.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:29:49.927+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:29:49.897+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:29:49.936+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:29:49.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.109 seconds
[2022-12-15T00:30:20.717+0000] {processor.py:153} INFO - Started process (PID=5347) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:30:20.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:30:20.726+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:30:20.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:30:20.850+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:30:20.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:30:20.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:30:20.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.161 seconds
[2022-12-15T00:30:51.575+0000] {processor.py:153} INFO - Started process (PID=5411) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:30:51.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:30:51.580+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:30:51.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:30:51.660+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:30:51.649+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:30:51.671+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:30:51.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.116 seconds
[2022-12-15T00:31:21.782+0000] {processor.py:153} INFO - Started process (PID=5454) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:31:21.785+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:31:21.786+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:31:21.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:31:21.859+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:31:21.850+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:31:21.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:31:21.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.106 seconds
[2022-12-15T00:31:52.743+0000] {processor.py:153} INFO - Started process (PID=5518) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:31:52.746+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:31:52.747+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:31:52.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:31:52.828+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:31:52.809+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:31:52.837+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:31:52.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.138 seconds
[2022-12-15T00:32:23.147+0000] {processor.py:153} INFO - Started process (PID=5562) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:32:23.151+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:32:23.153+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:32:23.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:32:23.202+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:32:23.194+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:32:23.207+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:32:23.223+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.079 seconds
[2022-12-15T00:32:53.399+0000] {processor.py:153} INFO - Started process (PID=5626) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:32:53.402+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:32:53.403+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:32:53.403+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:32:53.496+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:32:53.472+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:32:53.506+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:32:53.534+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.137 seconds
[2022-12-15T00:33:24.496+0000] {processor.py:153} INFO - Started process (PID=5670) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:33:24.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:33:24.499+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:33:24.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:33:24.572+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:33:24.557+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:33:24.578+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:33:24.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T00:33:54.870+0000] {processor.py:153} INFO - Started process (PID=5734) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:33:54.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:33:54.876+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:33:54.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:33:54.965+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:33:54.949+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:33:54.972+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:33:54.991+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.123 seconds
[2022-12-15T00:34:25.252+0000] {processor.py:153} INFO - Started process (PID=5787) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:34:25.255+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:34:25.256+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:34:25.256+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:34:25.337+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:34:25.325+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:34:25.349+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:34:25.364+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.114 seconds
[2022-12-15T00:34:56.058+0000] {processor.py:153} INFO - Started process (PID=5842) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:34:56.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:34:56.063+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:34:56.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:34:56.111+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:34:56.100+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:34:56.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:34:56.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.078 seconds
[2022-12-15T00:35:26.783+0000] {processor.py:153} INFO - Started process (PID=5906) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:35:26.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:35:26.787+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:35:26.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:35:26.870+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:35:26.847+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:35:26.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:35:26.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.115 seconds
[2022-12-15T00:35:57.257+0000] {processor.py:153} INFO - Started process (PID=5950) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:35:57.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:35:57.261+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:35:57.261+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:35:57.314+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:35:57.304+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:35:57.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:35:57.333+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.078 seconds
[2022-12-15T00:36:28.098+0000] {processor.py:153} INFO - Started process (PID=6014) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:36:28.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:36:28.105+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:36:28.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:36:28.167+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:36:28.152+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:36:28.175+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:36:28.191+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.096 seconds
[2022-12-15T00:36:58.345+0000] {processor.py:153} INFO - Started process (PID=6058) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:36:58.348+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:36:58.349+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:36:58.349+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:36:58.391+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:36:58.382+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:36:58.398+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:36:58.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.073 seconds
[2022-12-15T00:37:28.588+0000] {processor.py:153} INFO - Started process (PID=6122) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:37:28.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:37:28.593+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:37:28.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:37:28.661+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:37:28.650+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:37:28.666+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:37:28.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.096 seconds
[2022-12-15T00:37:58.769+0000] {processor.py:153} INFO - Started process (PID=6167) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:37:58.771+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:37:58.772+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:37:58.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:37:58.830+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:37:58.819+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:37:58.835+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:37:58.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.087 seconds
[2022-12-15T00:38:29.539+0000] {processor.py:153} INFO - Started process (PID=6231) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:38:29.541+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:38:29.542+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:38:29.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:38:29.596+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:38:29.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:38:29.601+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:38:29.619+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.083 seconds
[2022-12-15T00:39:00.285+0000] {processor.py:153} INFO - Started process (PID=6275) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:39:00.287+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:39:00.288+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:39:00.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:39:00.344+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:39:00.328+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:39:00.349+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:39:00.367+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.085 seconds
[2022-12-15T00:39:30.450+0000] {processor.py:153} INFO - Started process (PID=6339) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:39:30.453+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:39:30.454+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:39:30.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:39:30.515+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:39:30.503+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:39:30.520+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:39:30.538+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.090 seconds
[2022-12-15T00:40:00.725+0000] {processor.py:153} INFO - Started process (PID=6384) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:40:00.728+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:40:00.730+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:40:00.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:40:00.793+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:40:00.784+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:40:00.798+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:40:00.815+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.093 seconds
[2022-12-15T00:40:30.961+0000] {processor.py:153} INFO - Started process (PID=6448) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:40:30.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:40:30.965+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:40:30.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:40:31.086+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:40:31.065+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:40:31.100+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:40:31.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.175 seconds
[2022-12-15T00:41:01.308+0000] {processor.py:153} INFO - Started process (PID=6492) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:41:01.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:41:01.312+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:41:01.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:41:01.399+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:41:01.381+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:41:01.405+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:41:01.425+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.119 seconds
[2022-12-15T00:41:31.631+0000] {processor.py:153} INFO - Started process (PID=6556) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:41:31.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:41:31.636+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:41:31.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:41:31.725+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:41:31.715+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:41:31.731+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:41:31.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.124 seconds
[2022-12-15T00:42:02.129+0000] {processor.py:153} INFO - Started process (PID=6601) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:42:02.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:42:02.134+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:42:02.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:42:02.222+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:42:02.202+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:42:02.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:42:02.248+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.122 seconds
[2022-12-15T00:42:32.990+0000] {processor.py:153} INFO - Started process (PID=6665) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:42:32.993+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:42:32.994+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:42:32.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:42:33.061+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:42:33.039+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:42:33.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:42:33.083+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.096 seconds
[2022-12-15T00:43:03.750+0000] {processor.py:153} INFO - Started process (PID=6709) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:43:03.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:43:03.753+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:43:03.753+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:43:03.807+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:43:03.799+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:43:03.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:43:03.833+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.086 seconds
[2022-12-15T00:43:33.946+0000] {processor.py:153} INFO - Started process (PID=6773) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:43:33.948+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:43:33.950+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:43:33.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:43:34.016+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:43:34.002+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:43:34.021+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:43:34.038+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.094 seconds
[2022-12-15T00:44:04.813+0000] {processor.py:153} INFO - Started process (PID=6817) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:44:04.817+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:44:04.818+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:44:04.818+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:44:04.899+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:44:04.883+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:44:04.906+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:44:04.924+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.114 seconds
[2022-12-15T00:44:34.985+0000] {processor.py:153} INFO - Started process (PID=6883) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:44:34.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:44:34.988+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:44:34.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:44:35.039+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:44:35.029+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:44:35.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:44:35.060+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.078 seconds
[2022-12-15T00:45:05.221+0000] {processor.py:153} INFO - Started process (PID=6927) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:45:05.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:45:05.224+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:45:05.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:45:05.258+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:45:05.251+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:45:05.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:45:05.279+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.061 seconds
[2022-12-15T00:45:35.897+0000] {processor.py:153} INFO - Started process (PID=6992) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:45:35.900+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:45:35.901+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:45:35.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:45:35.972+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:45:35.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:45:35.974+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:45:35.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.095 seconds
[2022-12-15T00:46:06.162+0000] {processor.py:153} INFO - Started process (PID=7036) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:46:06.164+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:46:06.166+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:46:06.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:46:06.237+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:46:06.225+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:46:06.242+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:46:06.307+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.147 seconds
[2022-12-15T00:46:36.494+0000] {processor.py:153} INFO - Started process (PID=7100) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:46:36.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:46:36.499+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:46:36.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:46:36.562+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:46:36.552+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:46:36.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:46:36.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.092 seconds
[2022-12-15T00:47:07.204+0000] {processor.py:153} INFO - Started process (PID=7144) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:47:07.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:47:07.208+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:47:07.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:47:07.292+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:47:07.276+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:47:07.297+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:47:07.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.114 seconds
[2022-12-15T00:47:37.437+0000] {processor.py:153} INFO - Started process (PID=7209) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:47:37.440+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:47:37.441+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:47:37.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:47:37.511+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:47:37.498+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:47:37.516+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:47:37.533+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.099 seconds
[2022-12-15T00:48:07.796+0000] {processor.py:153} INFO - Started process (PID=7253) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:48:07.798+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:48:07.800+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:48:07.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:48:07.862+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:48:07.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:48:07.866+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:48:07.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.094 seconds
[2022-12-15T00:48:38.130+0000] {processor.py:153} INFO - Started process (PID=7317) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:48:38.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:48:38.133+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:48:38.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:48:38.185+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:48:38.176+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:48:38.189+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:48:38.260+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.133 seconds
[2022-12-15T00:49:08.330+0000] {processor.py:153} INFO - Started process (PID=7361) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:49:08.340+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:49:08.341+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:49:08.341+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:49:08.413+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:49:08.400+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:49:08.417+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:49:08.498+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.170 seconds
[2022-12-15T00:49:39.309+0000] {processor.py:153} INFO - Started process (PID=7425) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:49:39.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:49:39.318+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:49:39.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:49:39.390+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:49:39.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:49:39.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:49:39.433+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.126 seconds
[2022-12-15T00:50:09.904+0000] {processor.py:153} INFO - Started process (PID=7490) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:50:09.908+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:50:09.909+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:50:09.909+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:50:09.949+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:50:09.941+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:50:09.953+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:50:09.971+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.070 seconds
[2022-12-15T00:50:40.635+0000] {processor.py:153} INFO - Started process (PID=7534) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:50:40.637+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:50:40.639+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:50:40.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:50:40.692+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:50:40.681+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:50:40.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:50:40.713+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.080 seconds
[2022-12-15T00:51:10.775+0000] {processor.py:153} INFO - Started process (PID=7598) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:51:10.778+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:51:10.779+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:51:10.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:51:10.808+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:51:10.803+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:51:10.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:51:10.826+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.053 seconds
[2022-12-15T00:51:41.027+0000] {processor.py:153} INFO - Started process (PID=7642) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:51:41.032+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:51:41.034+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:51:41.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:51:41.132+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:51:41.114+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:51:41.138+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:51:41.155+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.131 seconds
[2022-12-15T00:52:11.909+0000] {processor.py:153} INFO - Started process (PID=7706) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:52:11.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:52:11.926+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:52:11.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:52:11.996+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:52:11.980+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:52:12.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:52:12.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.129 seconds
[2022-12-15T00:52:42.574+0000] {processor.py:153} INFO - Started process (PID=7750) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:52:42.577+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:52:42.579+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:52:42.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:52:42.641+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:52:42.632+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:52:42.646+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:52:42.670+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.099 seconds
[2022-12-15T00:53:13.338+0000] {processor.py:153} INFO - Started process (PID=7815) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:53:13.340+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:53:13.341+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:53:13.341+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:53:13.373+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:53:13.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:53:13.375+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:53:13.391+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.055 seconds
[2022-12-15T00:53:43.926+0000] {processor.py:153} INFO - Started process (PID=7859) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:53:43.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:53:43.929+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:53:43.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:53:43.960+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:53:43.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:53:43.962+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:53:43.977+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.053 seconds
[2022-12-15T00:54:14.618+0000] {processor.py:153} INFO - Started process (PID=7924) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:54:14.621+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:54:14.622+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:54:14.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:54:14.671+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:54:14.662+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:54:14.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:54:14.695+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.080 seconds
[2022-12-15T00:54:45.407+0000] {processor.py:153} INFO - Started process (PID=7968) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:54:45.411+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:54:45.412+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:54:45.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:54:45.464+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:54:45.454+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:54:45.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:54:45.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.081 seconds
[2022-12-15T00:55:16.072+0000] {processor.py:153} INFO - Started process (PID=8033) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:55:16.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:55:16.076+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:55:16.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:55:16.112+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:55:16.105+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:55:16.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:55:16.130+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.061 seconds
[2022-12-15T00:55:46.800+0000] {processor.py:153} INFO - Started process (PID=8077) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:55:46.802+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:55:46.803+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:55:46.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:55:46.866+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:55:46.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:55:46.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:55:46.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.093 seconds
[2022-12-15T00:56:17.175+0000] {processor.py:153} INFO - Started process (PID=8142) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:56:17.178+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:56:17.179+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:56:17.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:56:17.210+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:56:17.204+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:56:17.212+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:56:17.229+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.056 seconds
[2022-12-15T00:56:47.852+0000] {processor.py:153} INFO - Started process (PID=8206) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:56:47.854+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:56:47.856+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:56:47.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:56:47.904+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:56:47.895+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:56:47.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:56:47.930+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.080 seconds
[2022-12-15T00:57:18.537+0000] {processor.py:153} INFO - Started process (PID=8250) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:57:18.539+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:57:18.542+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:57:18.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:57:18.590+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:57:18.579+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:57:18.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:57:18.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.084 seconds
[2022-12-15T00:57:49.286+0000] {processor.py:153} INFO - Started process (PID=8315) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:57:49.291+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:57:49.293+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:57:49.293+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:57:49.368+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:57:49.354+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:57:49.374+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:57:49.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.110 seconds
[2022-12-15T00:58:19.963+0000] {processor.py:153} INFO - Started process (PID=8359) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:58:19.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:58:19.968+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:58:19.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:58:20.014+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:58:20.006+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:58:20.018+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:58:20.036+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.075 seconds
[2022-12-15T00:58:50.570+0000] {processor.py:153} INFO - Started process (PID=8423) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:58:50.574+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:58:50.575+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:58:50.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:58:50.625+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:58:50.615+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:58:50.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:58:50.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.079 seconds
[2022-12-15T00:59:21.277+0000] {processor.py:153} INFO - Started process (PID=8467) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:59:21.280+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:59:21.281+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:59:21.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:59:21.317+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:59:21.309+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:59:21.320+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:59:21.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.063 seconds
[2022-12-15T00:59:51.951+0000] {processor.py:153} INFO - Started process (PID=8531) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:59:51.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T00:59:51.955+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:59:51.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:59:52.029+0000] {logging_mixin.py:137} INFO - [2022-12-15T00:59:52.019+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T00:59:52.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T00:59:52.050+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T01:00:22.682+0000] {processor.py:153} INFO - Started process (PID=8575) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:00:22.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:00:22.685+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:00:22.685+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:00:22.738+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:00:22.727+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:00:22.742+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:00:22.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.081 seconds
[2022-12-15T01:00:53.390+0000] {processor.py:153} INFO - Started process (PID=8639) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:00:53.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:00:53.393+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:00:53.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:00:53.424+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:00:53.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:00:53.426+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:00:53.442+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.054 seconds
[2022-12-15T01:01:23.962+0000] {processor.py:153} INFO - Started process (PID=8683) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:01:23.965+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:01:23.967+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:01:23.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:01:24.055+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:01:24.037+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:01:24.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:01:24.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.126 seconds
[2022-12-15T01:01:54.705+0000] {processor.py:153} INFO - Started process (PID=8748) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:01:54.709+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:01:54.710+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:01:54.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:01:54.750+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:01:54.742+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:01:54.752+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:01:54.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.068 seconds
[2022-12-15T01:02:25.363+0000] {processor.py:153} INFO - Started process (PID=8792) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:02:25.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:02:25.367+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:02:25.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:02:25.411+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:02:25.400+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:02:25.415+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:02:25.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.072 seconds
[2022-12-15T01:02:56.196+0000] {processor.py:153} INFO - Started process (PID=8856) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:02:56.199+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:02:56.200+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:02:56.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:02:56.244+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:02:56.230+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:02:56.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:02:56.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.072 seconds
[2022-12-15T01:03:26.878+0000] {processor.py:153} INFO - Started process (PID=8909) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:03:26.879+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:03:26.885+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:03:26.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:03:26.944+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:03:26.932+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:03:26.947+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:03:26.969+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.094 seconds
[2022-12-15T01:03:57.545+0000] {processor.py:153} INFO - Started process (PID=8964) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:03:57.547+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:03:57.548+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:03:57.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:03:57.619+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:03:57.607+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:03:57.625+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:03:57.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.104 seconds
[2022-12-15T01:04:28.266+0000] {processor.py:153} INFO - Started process (PID=9028) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:04:28.269+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:04:28.270+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:04:28.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:04:28.322+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:04:28.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:04:28.325+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:04:28.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.080 seconds
[2022-12-15T01:04:59.339+0000] {processor.py:153} INFO - Started process (PID=9074) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:04:59.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:04:59.344+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:04:59.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:04:59.401+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:04:59.388+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:04:59.405+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:04:59.421+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.084 seconds
[2022-12-15T01:05:30.006+0000] {processor.py:153} INFO - Started process (PID=9138) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:05:30.009+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:05:30.010+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:05:30.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:05:30.138+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:05:30.112+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:05:30.144+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:05:30.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.159 seconds
[2022-12-15T01:06:00.330+0000] {processor.py:153} INFO - Started process (PID=9182) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:06:00.332+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:06:00.333+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:06:00.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:06:00.367+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:06:00.360+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:06:00.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:06:00.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.059 seconds
[2022-12-15T01:06:30.943+0000] {processor.py:153} INFO - Started process (PID=9246) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:06:30.953+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:06:30.954+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:06:30.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:06:31.026+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:06:31.011+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:06:31.031+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:06:31.050+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.110 seconds
[2022-12-15T01:07:01.980+0000] {processor.py:153} INFO - Started process (PID=9290) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:07:01.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:07:01.985+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:07:01.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:07:02.051+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:07:02.038+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:07:02.057+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:07:02.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.101 seconds
[2022-12-15T01:07:32.747+0000] {processor.py:153} INFO - Started process (PID=9354) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:07:32.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:07:32.751+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:07:32.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:07:32.800+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:07:32.790+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:07:32.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:07:32.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.077 seconds
[2022-12-15T01:08:03.441+0000] {processor.py:153} INFO - Started process (PID=9398) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:08:03.445+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:08:03.446+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:08:03.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:08:03.491+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:08:03.481+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:08:03.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:08:03.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.078 seconds
[2022-12-15T01:08:34.081+0000] {processor.py:153} INFO - Started process (PID=9462) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:08:34.088+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:08:34.090+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:08:34.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:08:34.158+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:08:34.148+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:08:34.162+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:08:34.179+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T01:09:04.359+0000] {processor.py:153} INFO - Started process (PID=9507) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:09:04.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:09:04.364+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:09:04.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:09:04.433+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:09:04.419+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:09:04.439+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:09:04.463+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.109 seconds
[2022-12-15T01:09:34.664+0000] {processor.py:153} INFO - Started process (PID=9571) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:09:34.667+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:09:34.668+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:09:34.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:09:34.741+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:09:34.731+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:09:34.746+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:09:34.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.102 seconds
[2022-12-15T01:10:05.313+0000] {processor.py:153} INFO - Started process (PID=9615) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:10:05.315+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:10:05.316+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:10:05.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:10:05.353+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:10:05.346+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:10:05.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:10:05.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.072 seconds
[2022-12-15T01:10:35.487+0000] {processor.py:153} INFO - Started process (PID=9681) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:10:35.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-15T01:10:35.491+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:10:35.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:10:35.571+0000] {logging_mixin.py:137} INFO - [2022-12-15T01:10:35.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-15T01:10:35.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-15T01:10:35.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.112 seconds
