[2022-12-14T23:40:51.962+0000] {processor.py:153} INFO - Started process (PID=47) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:40:51.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:40:51.966+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:40:51.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:40:52.031+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:40:52.017+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:40:52.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:40:52.061+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.105 seconds
[2022-12-14T23:41:23.055+0000] {processor.py:153} INFO - Started process (PID=99) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:41:23.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:41:23.103+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:41:23.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:41:24.130+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:41:24.076+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:41:24.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:41:24.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 1.193 seconds
[2022-12-14T23:41:54.628+0000] {processor.py:153} INFO - Started process (PID=155) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:41:54.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:41:54.674+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:41:54.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:41:54.850+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:41:54.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:41:54.859+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:41:54.914+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.290 seconds
[2022-12-14T23:42:25.361+0000] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:42:25.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:42:25.378+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:42:25.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:42:25.444+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:42:25.432+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:42:25.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:42:25.467+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.108 seconds
[2022-12-14T23:42:56.157+0000] {processor.py:153} INFO - Started process (PID=263) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:42:56.160+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:42:56.162+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:42:56.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:42:56.240+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:42:56.226+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:42:56.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:42:56.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.114 seconds
[2022-12-14T23:43:26.955+0000] {processor.py:153} INFO - Started process (PID=307) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:43:26.960+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:43:26.962+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:43:26.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:43:27.052+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:43:27.038+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:43:27.058+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:43:27.076+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.124 seconds
[2022-12-14T23:43:57.776+0000] {processor.py:153} INFO - Started process (PID=371) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:43:57.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:43:57.780+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:43:57.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:43:57.851+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:43:57.841+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:43:57.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:43:57.939+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.167 seconds
[2022-12-14T23:44:28.041+0000] {processor.py:153} INFO - Started process (PID=414) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:44:28.048+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:44:28.049+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:44:28.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:44:28.132+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:44:28.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:44:28.139+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:44:28.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.180 seconds
[2022-12-14T23:44:58.709+0000] {processor.py:153} INFO - Started process (PID=479) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:44:58.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:44:58.713+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:44:58.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:44:58.822+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:44:58.797+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:44:58.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:44:58.852+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.147 seconds
[2022-12-14T23:45:29.669+0000] {processor.py:153} INFO - Started process (PID=523) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:45:29.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:45:29.674+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:45:29.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:45:29.776+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:45:29.753+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:45:29.783+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:45:29.803+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.136 seconds
[2022-12-14T23:46:00.481+0000] {processor.py:153} INFO - Started process (PID=587) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:46:00.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:46:00.486+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:46:00.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:46:00.574+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:46:00.557+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:46:00.583+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:46:00.602+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.123 seconds
[2022-12-14T23:46:31.379+0000] {processor.py:153} INFO - Started process (PID=631) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:46:31.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:46:31.384+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:46:31.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:46:31.475+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:46:31.458+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:46:31.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:46:31.509+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.132 seconds
[2022-12-14T23:47:02.277+0000] {processor.py:153} INFO - Started process (PID=695) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:47:02.282+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:47:02.284+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:47:02.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:47:02.384+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:47:02.363+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:47:02.395+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:47:02.414+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.140 seconds
[2022-12-14T23:47:33.274+0000] {processor.py:153} INFO - Started process (PID=746) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:47:33.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:47:33.278+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:47:33.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:47:33.368+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:47:33.347+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:47:33.375+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:47:33.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.120 seconds
[2022-12-14T23:48:04.132+0000] {processor.py:153} INFO - Started process (PID=803) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:48:04.135+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:48:04.137+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:48:04.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:48:04.239+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:48:04.221+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:48:04.244+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:48:04.258+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.129 seconds
[2022-12-14T23:48:35.099+0000] {processor.py:153} INFO - Started process (PID=856) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:48:35.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:48:35.103+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:48:35.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:48:35.186+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:48:35.170+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:48:35.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:48:35.218+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.122 seconds
[2022-12-14T23:49:05.419+0000] {processor.py:153} INFO - Started process (PID=911) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:49:05.421+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:49:05.422+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:49:05.421+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:49:05.485+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:49:05.476+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:49:05.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:49:05.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.088 seconds
[2022-12-14T23:49:35.761+0000] {processor.py:153} INFO - Started process (PID=964) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:49:35.763+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:49:35.765+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:49:35.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:49:35.822+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:49:35.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:49:35.833+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:49:35.857+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.099 seconds
[2022-12-14T23:50:06.504+0000] {processor.py:153} INFO - Started process (PID=1019) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:50:06.507+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:50:06.508+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:50:06.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:50:06.595+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:50:06.577+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:50:06.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:50:06.627+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.127 seconds
[2022-12-14T23:50:36.756+0000] {processor.py:153} INFO - Started process (PID=1084) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:50:36.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:50:36.761+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:50:36.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:50:36.801+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:50:36.793+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:50:36.805+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:50:36.823+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.068 seconds
[2022-12-14T23:51:07.182+0000] {processor.py:153} INFO - Started process (PID=1128) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:51:07.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:51:07.187+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:51:07.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:51:07.249+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:51:07.240+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:51:07.256+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:51:07.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.098 seconds
[2022-12-14T23:51:37.457+0000] {processor.py:153} INFO - Started process (PID=1192) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:51:37.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:51:37.460+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:51:37.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:51:37.508+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:51:37.498+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:51:37.513+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:51:37.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.073 seconds
[2022-12-14T23:52:08.028+0000] {processor.py:153} INFO - Started process (PID=1236) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:52:08.030+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:52:08.030+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:52:08.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:52:08.143+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:52:08.114+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:52:08.154+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:52:08.176+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.150 seconds
[2022-12-14T23:52:38.638+0000] {processor.py:153} INFO - Started process (PID=1300) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:52:38.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:52:38.642+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:52:38.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:52:38.742+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:52:38.723+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:52:38.751+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:52:38.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.135 seconds
[2022-12-14T23:53:08.941+0000] {processor.py:153} INFO - Started process (PID=1344) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:53:08.944+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:53:08.945+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:53:08.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:53:09.031+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:53:09.012+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:53:09.040+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:53:09.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.124 seconds
[2022-12-14T23:53:39.866+0000] {processor.py:153} INFO - Started process (PID=1408) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:53:39.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:53:39.871+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:53:39.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:53:39.955+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:53:39.939+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:53:39.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:53:39.983+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.120 seconds
[2022-12-14T23:54:10.735+0000] {processor.py:153} INFO - Started process (PID=1452) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:54:10.738+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:54:10.739+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:54:10.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:54:10.837+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:54:10.814+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:54:10.845+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:54:10.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.129 seconds
[2022-12-14T23:54:41.502+0000] {processor.py:153} INFO - Started process (PID=1516) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:54:41.506+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:54:41.507+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:54:41.507+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:54:41.586+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:54:41.571+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:54:41.593+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:54:41.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.114 seconds
[2022-12-14T23:55:12.179+0000] {processor.py:153} INFO - Started process (PID=1570) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:55:12.184+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:55:12.185+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:55:12.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:55:12.247+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:55:12.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:55:12.252+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:55:12.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.093 seconds
[2022-12-14T23:55:42.874+0000] {processor.py:153} INFO - Started process (PID=1625) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:55:42.880+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:55:42.881+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:55:42.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:55:42.960+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:55:42.942+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:55:42.966+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:55:42.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.120 seconds
[2022-12-14T23:56:13.117+0000] {processor.py:153} INFO - Started process (PID=1677) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:56:13.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:56:13.121+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:56:13.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:56:13.238+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:56:13.188+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:56:13.243+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:56:13.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.155 seconds
[2022-12-14T23:56:43.456+0000] {processor.py:153} INFO - Started process (PID=1732) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:56:43.460+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:56:43.463+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:56:43.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:56:43.584+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:56:43.559+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:56:43.593+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:56:43.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.179 seconds
[2022-12-14T23:57:14.085+0000] {processor.py:153} INFO - Started process (PID=1777) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:57:14.087+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:57:14.089+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:57:14.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:57:14.170+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:57:14.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:57:14.178+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:57:14.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.117 seconds
[2022-12-14T23:57:44.807+0000] {processor.py:153} INFO - Started process (PID=1840) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:57:44.818+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:57:44.820+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:57:44.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:57:44.905+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:57:44.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:57:44.909+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:57:44.927+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.123 seconds
[2022-12-14T23:58:15.236+0000] {processor.py:153} INFO - Started process (PID=1883) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:58:15.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:58:15.245+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:58:15.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:58:15.341+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:58:15.325+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:58:15.348+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:58:15.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.134 seconds
[2022-12-14T23:58:45.670+0000] {processor.py:153} INFO - Started process (PID=1946) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:58:45.673+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:58:45.674+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:58:45.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:58:45.793+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:58:45.766+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:58:45.801+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:58:45.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.165 seconds
[2022-12-14T23:59:16.064+0000] {processor.py:153} INFO - Started process (PID=1989) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:59:16.070+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:59:16.072+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:59:16.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:59:16.242+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:59:16.201+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:59:16.259+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:59:16.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.225 seconds
[2022-12-14T23:59:46.466+0000] {processor.py:153} INFO - Started process (PID=2053) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:59:46.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2022-12-14T23:59:46.470+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:59:46.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:59:46.550+0000] {logging_mixin.py:137} INFO - [2022-12-14T23:59:46.537+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-12-14T23:59:46.555+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2022-12-14T23:59:46.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.110 seconds
