[2023-02-14T00:32:44.646+0000] {processor.py:153} INFO - Started process (PID=54) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:32:44.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:32:44.651+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:32:44.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:32:44.724+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:32:44.708+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:32:44.733+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:32:44.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.113 seconds
[2023-02-14T00:33:14.931+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:33:14.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:33:14.935+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:33:14.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:33:15.013+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:33:14.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:33:15.019+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:33:15.043+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.114 seconds
[2023-02-14T00:33:45.629+0000] {processor.py:153} INFO - Started process (PID=154) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:33:45.632+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:33:45.633+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:33:45.633+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:33:45.694+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:33:45.684+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:33:45.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:33:45.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.091 seconds
[2023-02-14T00:34:16.300+0000] {processor.py:153} INFO - Started process (PID=218) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:34:16.301+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:34:16.302+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:34:16.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:34:16.335+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:34:16.328+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:34:16.338+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:34:16.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.061 seconds
[2023-02-14T00:34:46.872+0000] {processor.py:153} INFO - Started process (PID=271) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:34:46.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:34:46.877+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:34:46.877+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:34:46.931+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:34:46.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:34:46.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:34:46.956+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.086 seconds
[2023-02-14T00:35:17.404+0000] {processor.py:153} INFO - Started process (PID=326) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:35:17.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:35:17.407+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:35:17.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:35:17.440+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:35:17.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:35:17.443+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:35:17.460+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.057 seconds
[2023-02-14T00:35:47.923+0000] {processor.py:153} INFO - Started process (PID=390) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:35:47.926+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:35:47.927+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:35:47.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:35:47.980+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:35:47.970+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:35:47.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:35:48.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.079 seconds
[2023-02-14T00:36:18.557+0000] {processor.py:153} INFO - Started process (PID=434) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:36:18.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:36:18.560+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:36:18.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:36:18.598+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:36:18.591+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:36:18.602+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:36:18.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.063 seconds
[2023-02-14T00:36:49.201+0000] {processor.py:153} INFO - Started process (PID=499) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:36:49.203+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:36:49.205+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:36:49.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:36:49.248+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:36:49.238+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:36:49.252+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:36:49.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.071 seconds
[2023-02-14T00:37:19.726+0000] {processor.py:153} INFO - Started process (PID=543) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:37:19.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:37:19.730+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:37:19.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:37:19.767+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:37:19.761+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:37:19.770+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:37:19.786+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.062 seconds
[2023-02-14T00:37:50.181+0000] {processor.py:153} INFO - Started process (PID=610) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:37:50.184+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:37:50.185+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:37:50.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:37:50.257+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:37:50.242+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:37:50.262+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:37:50.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.110 seconds
[2023-02-14T00:38:20.838+0000] {processor.py:153} INFO - Started process (PID=660) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:38:20.840+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:38:20.841+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:38:20.841+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:38:20.900+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:38:20.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:38:20.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:38:20.923+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.087 seconds
[2023-02-14T00:38:51.525+0000] {processor.py:153} INFO - Started process (PID=719) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:38:51.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:38:51.528+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:38:51.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:38:51.559+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:38:51.553+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:38:51.562+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:38:51.578+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.055 seconds
[2023-02-14T00:39:21.999+0000] {processor.py:153} INFO - Started process (PID=770) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:39:22.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:39:22.003+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:39:22.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:39:22.070+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:39:22.055+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:39:22.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:39:22.104+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.107 seconds
[2023-02-14T00:39:52.472+0000] {processor.py:153} INFO - Started process (PID=827) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:39:52.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:39:52.475+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:39:52.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:39:52.514+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:39:52.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:39:52.517+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:39:52.534+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.065 seconds
[2023-02-14T00:40:23.083+0000] {processor.py:153} INFO - Started process (PID=891) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:40:23.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:40:23.087+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:40:23.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:40:23.151+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:40:23.137+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:40:23.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:40:23.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.110 seconds
[2023-02-14T00:40:53.723+0000] {processor.py:153} INFO - Started process (PID=935) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:40:53.732+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:40:53.733+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:40:53.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:40:53.767+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:40:53.761+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:40:53.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:40:53.793+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.072 seconds
[2023-02-14T00:41:24.298+0000] {processor.py:153} INFO - Started process (PID=999) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:41:24.299+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:41:24.300+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:41:24.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:41:24.360+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:41:24.343+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:41:24.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:41:24.388+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.092 seconds
[2023-02-14T00:41:54.830+0000] {processor.py:153} INFO - Started process (PID=1043) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:41:54.832+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:41:54.833+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:41:54.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:41:54.878+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:41:54.863+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:41:54.882+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:41:54.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.070 seconds
[2023-02-14T00:42:25.438+0000] {processor.py:153} INFO - Started process (PID=1107) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:42:25.441+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:42:25.442+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:42:25.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:42:25.512+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:42:25.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:42:25.518+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:42:25.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.100 seconds
[2023-02-14T00:42:55.680+0000] {processor.py:153} INFO - Started process (PID=1150) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:42:55.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:42:55.683+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:42:55.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:42:55.714+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:42:55.707+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:42:55.718+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:42:55.734+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.056 seconds
[2023-02-14T00:43:26.278+0000] {processor.py:153} INFO - Started process (PID=1214) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:43:26.280+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:43:26.281+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:43:26.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:43:26.339+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:43:26.323+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:43:26.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:43:26.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.090 seconds
[2023-02-14T00:43:56.771+0000] {processor.py:153} INFO - Started process (PID=1278) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:43:56.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:43:56.775+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:43:56.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:43:56.821+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:43:56.809+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:43:56.826+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:43:56.844+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.076 seconds
[2023-02-14T00:44:27.281+0000] {processor.py:153} INFO - Started process (PID=1322) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:44:27.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:44:27.284+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:44:27.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:44:27.341+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:44:27.327+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:44:27.347+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:44:27.367+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.088 seconds
[2023-02-14T00:44:57.801+0000] {processor.py:153} INFO - Started process (PID=1386) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:44:57.803+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:44:57.804+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:44:57.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:44:57.866+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:44:57.848+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:44:57.872+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:44:57.938+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.140 seconds
[2023-02-14T00:45:28.387+0000] {processor.py:153} INFO - Started process (PID=1430) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:45:28.389+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:45:28.389+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:45:28.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:45:28.427+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:45:28.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:45:28.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:45:28.448+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.063 seconds
[2023-02-14T00:45:58.908+0000] {processor.py:153} INFO - Started process (PID=1494) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:45:58.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:45:58.912+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:45:58.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:45:58.989+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:45:58.973+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:45:59.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:45:59.046+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.142 seconds
[2023-02-14T00:46:29.491+0000] {processor.py:153} INFO - Started process (PID=1538) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:46:29.493+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:46:29.494+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:46:29.494+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:46:29.531+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:46:29.524+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:46:29.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:46:29.551+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.062 seconds
[2023-02-14T00:47:00.067+0000] {processor.py:153} INFO - Started process (PID=1602) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:47:00.069+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:47:00.071+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:47:00.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:47:00.124+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:47:00.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:47:00.127+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:47:00.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.081 seconds
[2023-02-14T00:47:30.563+0000] {processor.py:153} INFO - Started process (PID=1667) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:47:30.565+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:47:30.567+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:47:30.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:47:30.629+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:47:30.615+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:47:30.635+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:47:30.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.101 seconds
[2023-02-14T00:48:00.801+0000] {processor.py:153} INFO - Started process (PID=1711) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:48:00.802+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:48:00.803+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:48:00.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:48:00.834+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:48:00.827+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:48:00.837+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:48:00.866+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.068 seconds
[2023-02-14T00:48:31.404+0000] {processor.py:153} INFO - Started process (PID=1775) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:48:31.407+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:48:31.408+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:48:31.408+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:48:31.463+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:48:31.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:48:31.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:48:31.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.082 seconds
[2023-02-14T00:49:01.939+0000] {processor.py:153} INFO - Started process (PID=1819) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:49:01.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:49:01.941+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:49:01.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:49:01.973+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:49:01.967+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:49:01.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:49:01.993+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.056 seconds
[2023-02-14T00:49:32.478+0000] {processor.py:153} INFO - Started process (PID=1883) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:49:32.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:49:32.482+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:49:32.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:49:32.550+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:49:32.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:49:32.554+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:49:32.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.098 seconds
[2023-02-14T00:50:03.036+0000] {processor.py:153} INFO - Started process (PID=1927) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:50:03.039+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:50:03.040+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:50:03.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:50:03.087+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:50:03.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:50:03.091+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:50:03.111+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.077 seconds
[2023-02-14T00:50:33.679+0000] {processor.py:153} INFO - Started process (PID=1991) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:50:33.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:50:33.681+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:50:33.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:50:33.715+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:50:33.708+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:50:33.718+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:50:33.735+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.058 seconds
[2023-02-14T00:51:04.215+0000] {processor.py:153} INFO - Started process (PID=2035) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:51:04.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:51:04.218+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:51:04.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:51:04.252+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:51:04.242+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:51:04.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:51:04.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.062 seconds
[2023-02-14T00:51:34.736+0000] {processor.py:153} INFO - Started process (PID=2099) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:51:34.738+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:51:34.740+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:51:34.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:51:34.804+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:51:34.791+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:51:34.809+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:51:34.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.096 seconds
[2023-02-14T00:52:05.286+0000] {processor.py:153} INFO - Started process (PID=2164) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:52:05.290+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:52:05.291+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:52:05.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:52:05.351+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:52:05.340+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:52:05.358+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:52:05.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.096 seconds
[2023-02-14T00:52:35.976+0000] {processor.py:153} INFO - Started process (PID=2208) to work on /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:52:35.978+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_validation.py for tasks to queue
[2023-02-14T00:52:35.979+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:52:35.979+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:52:36.039+0000] {logging_mixin.py:137} INFO - [2023-02-14T00:52:36.027+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_validation.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_validation.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-02-14T00:52:36.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_validation.py
[2023-02-14T00:52:36.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_validation.py took 0.093 seconds
